routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* =========== MIDDLEWARE AUTH =========== */
Route::middleware(['web'])->group(function () {
    
        /* ===== LOGIN PAGE ===== */
    Route::get('/', function () {
        return view('auth.login');
    })->name('login_view')->middleware('guest');

    Route::post('login','EmployeeController@login_post')->name('login');

    Route::middleware(['auth'])->group(function () {
        /* =========== DASHBOARD =========== */
        Route::get('dashboard','DashboardController@index')->name('dashboard');

        /* =========== AUTH =========== */
        Route::get('logout','EmployeeController@logout')->name('logout');
        /* =========== END AUTH =========== */

        /* =========== MASTER =========== */
        Route::middleware(['role:superadmin'])->group(function () {
            Route::resources([
                'employee'           => 'EmployeeController',
                'benefit'            => 'BenefitController',
            ]);
        });

        Route::middleware(['role:superadmin,finance,employee'])->group(function () {
            Route::resources([
                'claim'      => 'ReimbursementController',
            ]);

            Route::get('get_tr_benefit','TrBenefitController@create')->name('get_tr');
        });

        Route::middleware(['role:superadmin,finance'])->group(function () {
            Route::get('index_validation','ReimbursementController@index_validation')->name('index_val');
            Route::patch('approve/{approve}','ReimbursementController@approve')->name('approve');
            Route::delete('reject/{id}','ReimbursementController@reject')->name('reject');
        });
        
    });

});

app/Models/Reimbursement.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Reimbursement extends Model
{
    use HasFactory;

    protected $table = 'reimbursement';

    protected $primaryKey = 'id_reimbursement';

    public $incrementing = true;

    public $fillable = [
        'id_employee',
        'id_benefit',
        'total_claim',
        'description',
        'claim_status',
        'prove',
        'reference_number',
        'created_at',
        'updated_at'
    ];
}

app/Http/Controllers/ReimbursementController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Carbon\Carbon;

use App\Models\Benefit;
use App\Models\Tr_benefit;
use App\Models\Employee;
use App\Models\Reimbursement;

use Yajra\Datatables\Datatables;
use Intervention\Image\ImageManagerStatic as Image;

class ReimbursementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('reimbursement.request.request');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        $reimbursement = Reimbursement::orderBy('created_at','desc')->get();

        return Datatables::of($reimbursement)->editColumn('created_at', function($query) {
                            return $query->created_at->format('Y-M-d');
                        })->addColumn('year', function($query) {
                            return $query->created_at->format('Y');
                        })->make(true);
    
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validation_value = [
            'description'      => 'required|min:6|max:255',
            'total_claim'      => 'required|integer|gt:0',
            'benefit'          => 'required',
            "prove"            => "required|mimes:jpg,bmp,png|max:500000"
        ];

        $validator = Validator::make($request->all(),$validation_value);

        if ($validator->fails()) {
            return response()->json(['message'=>'Gagal menambah data','errors' => $validator->errors()],422);
        }

        $id_employee = Auth::user()->id_employee;

        /* PATH */
        $path = date("Y").'/'.date("m")."/";
        $destinationPath = public_path('assets/images/'.$path);
        
        if(!is_dir($destinationPath)) {
            mkdir($destinationPath, 0775, true);
        }

        /* COMPRESS IMAGE */
        if(!empty($request->prove)){
            $img = Image::make($request->prove);
        
            $img->resize(400, 400, function ($constraint) {
                $constraint->aspectRatio();
                $constraint->upsize();
            });

            $imgname = $id_employee."-".time(). '.' . $request->prove->getClientOriginalExtension();
        }else{
            $img = false;
            $imgname = $destinationPath.'default.jpg';
        }
        /* END COMPRESS IMAGE */
        
        /* UPLOAD IMAGE*/
        if($img){
            $img->save($destinationPath.$imgname,100);
            $imgname = $path.$imgname;
        }else{
            return response()->json(['message'=>'Gagal menyimpan gambar.'],422);
        }
        /* END UPLOAD IMAGE AND FILE */

        $data = [
            "description"      => $request->description,
            "total_claim"      => $request->total_claim,
            "id_employee"      => $id_employee,
            "id_benefit"       => $request->benefit,
            "claim_status"     => 0,
            "prove"            => $imgname,
            "reference_number" => null,
        ];

        $insert = Reimbursement::create($data);

        if($insert){
            return response()->json(['message'=>'Berhasil menambah data!'],200);
        }else{
            return response()->json(['message'=>'Gagal menambah data','errors' => $insert],422);
        }

        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Reimbursement  $reimbursement
     * @return \Illuminate\Http\Response
     */
    public function show(Reimbursement $reimbursement)
    {
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Reimbursement  $reimbursement
     * @return \Illuminate\Http\Response
     */
    public function edit(Reimbursement $reimbursement,Request $request)
    {
        $reimbursement = Reimbursement::find($request->id);
        return response()->json($reimbursement);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Reimbursement  $reimbursement
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Reimbursement $reimbursement)
    {
        $id = $request->id;

        $validation_value = [
            'description'      => 'required|min:6|max:255',
            'total_claim'      => 'required|integer|gt:0',
            'benefit'          => 'required',
            "prove"            => "required|mimes:jpg,bmp,png|max:500000"
        ];

        $validator = Validator::make($request->all(),$validation_value);

        if ($validator->fails()) {
            return response()->json(['message'=>'Gagal mengubah data','errors' => $validator->errors()],422);
        }

        $id_employee = Auth::user()->id_employee;

        /* PATH */
        $path = date("Y").'/'.date("m")."/";
        $destinationPath = public_path('assets/images/'.$path);
        
        if(!is_dir($destinationPath)) {
            mkdir($destinationPath, 0775, true);
        }

        /* COMPRESS IMAGE */
        if(!empty($request->prove)){

            $img = Image::make($request->prove);
        
            $img->resize(400, 400, function ($constraint) {
                $constraint->aspectRatio();
                $constraint->upsize();
            });

            $imgname = $id_employee."-".time(). '.' . $request->prove->getClientOriginalExtension();
        }else{
            $img = false;
            $imgname = $destinationPath.'default.jpg';
        }
        /* END COMPRESS IMAGE */

        $current_img = Reimbursement::find($request->id);
        
        /* UPLOAD IMAGE*/
        if($img){
          
            
            if(file_exists(public_path("assets/images/").$current_img->prove)){     
                unlink(public_path("assets/images/").$current_img->prove);
            }
         
            $img->save($destinationPath.$imgname,100);           
            $imgname = $path.$imgname;
        }else{
            $imgname = $current_img->prove;
        }
        /* END UPLOAD IMAGE AND FILE */

        $data = [
            "description"      => $request->description,
            "total_claim"      => $request->total_claim,
            "id_employee"      => $id_employee,
            "id_benefit"       => $request->benefit,
            "claim_status"     => 0,
            "prove"            => $imgname,
            "reference_number" => null,
        ];

        $update = Reimbursement::where('id_reimbursement',$id)->update($data);

        if($update){
            return response()->json(['message'=>'Berhasil mengubah data!'],200);
        }else{
            return response()->json(['message'=>'Gagal mengubah data','errors' => $update],422);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Reimbursement  $reimbursement
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $reimbursement = Reimbursement::find($id);

        if(file_exists(public_path("assets/images/").$reimbursement->prove)){     
            unlink(public_path("assets/images/").$reimbursement->prove);
        }

        $reimbursement->delete();
    }

    public function index_validation(){
        return view('reimbursement.validation.validation');
    }

    public function approve(Request $request){

        $id = $request->id;

        $reimbursement = Reimbursement::find($id);

        $id_benefit = $reimbursement->id_benefit;
        $id_employee = $reimbursement->id_employee;

        $data = [
            "claim_status"      => 1,
            "reference_number"  => $request->reference_number
        ];
        $update = Reimbursement::where('id_reimbursement',$id)->update($data);
        
        if($update){
            
            $used_balance = Reimbursement::select(DB::raw('SUM(total_claim) as used_balance'))->where('id_employee',$id_employee)->where('id_benefit',$id_benefit)->first();

            if(!empty($used_balance)){
                $used_balance = $used_balance->used_balance;
            }

            $current_balance = Tr_benefit::where('id_employee',$id_employee)
                                          ->where('id_benefit',$id_benefit)
                                          ->where(DB::raw('YEAR(created_at)'), '=', Carbon::now()->format('Y'))
                                          ->first();

        
            if(!empty($current_balance)){
                $current_balance = $current_balance->current_balance;
            }


            $current_balance = $current_balance - $used_balance;

            if($current_balance <= 0 ){
                $current_balance = 0;
            }

            $update_tr = [
                'used_balance'  => $used_balance,
                'current_balance' => $current_balance
            ];

            $update_tr_benefit = Tr_benefit::where('id_employee',$id_employee)
                                            ->where('id_benefit',$id_benefit)
                                            ->where(DB::raw('YEAR(created_at)'), '=', Carbon::now()->format('Y'))
                                            ->update($update_tr);

            return response()->json(['message'=>'Berhasil melakukan approve data!'],200);
        }else{
            return response()->json(['message'=>'Gagal melakukan approve data','errors' => $update],422);
        }
    }

    public function reject($id){

        $data = [
            "claim_status"     => 2,

resources/views/reimbursement/validation/validation.blade.php
@extends('layouts.dashboard')
@section('content')


<!-- Tittle -->
<div class="row">
    <div style="margin-bottom: 0.2rem;" class="col-12 grid-margin">
        <div style="height: 65px; border-radius: 15px;" class="card">
            <div class="card-body">
                <div style="display: flex; align-items: flex-start; justify-content: space-between; height: 40px;">
                    <h4 class="card-title" style="font-size: 2rem; font-weight: 300; margin-bottom: 0px;">Reimbursement</h4>
                    {{-- <button type="button" class="btn btn-success btn-rounded btn-icon" data-toggle="tooltip" data-placement="top" data-custom-class="tooltip-success" title="EDIT" data-target="#showModalUpdateAssetClass" style="margin-right:5px;"><i style="font-size:1.5rem; margin-left:-7px;" class="ti-pencil-alt"></i></button> --}}
                    <button style="margin: -0.2rem .05rem -1rem auto;" type="button" class="btn btn-primary btn-sm"
                        data-toggle="modal" data-target="#showModalInsertReimbursement"><i
                            class="ti-plus menu-icon"></i>&ensp;
                        ADD</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Table -->
<div class="row">
    <div style="margin-bottom: 0.2rem;" class="col-12 grid-margin">
        <div class="card" style="border-radius: 15px;">
                <div class="card-body">
                {{-- <h4 class="card-title">Data table</h4> --}}
                <div class="row">
                    <div class="col-12">
                    <div class="table-responsive">
                        <table id="reimburseTable" class="table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Year</th>
                                <th>Claim Date</th>
                                <th>Total Claim</th>
                                <th>Description</th>
                                <th>Prove</th>
                                <th>Claim Status</th>
                                <th>Reference Number</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        </table>
                    </div>
                    </div>
                </div>
                </div>
            </div>
    </div>
</div>
{{-- Table End --}}
@endsection

@section('jscustom')

<script>
    
    var mTable;

    $(document).ready(function () {
        
        mTable = $('#reimburseTable').DataTable({
            responsive: true,
            processing: true,
            "language": {
                "processing": "<div class='dot-opacity-loader'></div>"
            },
            "order": [[ 0, "desc" ]],
            serverSide: true,
            ajax: "{{ route('claim.create')}}",
            dom: 'Bfrtip',
            buttons: [
              
            ],
            columns: [
                {  
                    data: 'id_reimbursement',
                    render: function (data, type, row, meta) {
                        return meta.row + meta.settings._iDisplayStart + 1;
                    }
                },
                {
                    data: 'year',
                    name: 'year'
                },
                {
                    data: 'created_at',
                    name: 'created_at'
                },
                {
                    data: 'total_claim',
                    name: 'total_claim'
                },
                {
                    data: 'description',
                    name: 'description'
                },
                {  
                    data: 'prove',
                    render: function (data, type, row, meta) {
                        if(data != null){
                            return "<a href='{{ asset('assets/images') }}/"+data+"'>View</a>"
                        }else{
                            return null;
                        }
                    }
                },
                {  
                    data: 'claim_status',
                    render: function (data, type, row, meta) {
                        if(data != null){
                            if(data == 0 ){
                                return 'PENDING';
                            }else if(data == 1){
                                return 'APPROVED';
                            }else{
                                return 'REJECTED';
                            }
                        }else{
                            return null;
                        }
                    }
                },
                {
                    data: 'reference_number',
                    name: 'reference_number'
                },
                {
                    data: 'id_reimbursement',
                    render: function (data, type, row) {
                        let buttonApprove =
                            '<button type="button" class="btn btn-success btn-rounded btn-icon" data-toggle="modal" data-placement="buttom" data-custom-class="tooltip-success" title="Approve" data-target="#showModalUpdateApprove" style="margin-right:5px;" onclick="buttonEdit(\'' + data + '\');"><i style="font-size:1.5rem; margin-left:-7px;" class="ti-check"></i></button>';
                        let buttonReject =
                            '<button type="button" class="btn btn-danger btn-rounded btn-icon" data-toggle="tooltip" data-placement="bottom" data-custom-class="tooltip-success" title="Reject" onclick="delete_data(\''+
                            data +'\',\'reject\');"><i style="font-size:1.5rem; margin-left:-8px;" class="ti-close"></i></button>';
                        
                        if(row.claim_status == 1 || row.claim_status == 2 ){
                            return 'CLOSED'
                        }

                        return buttonApprove + buttonReject;
                    }
                }
            ]
        });

        //UPDATE Departement
        $('#formUpdateApprove').on('submit', function (e) {

            e.preventDefault();
            var url,data,form;

            url = 'approve';           //For routing
            data =  $(this).serialize();   // Data Form
            form = 'Approve';          // Reset Trigger and Close Modal

            swal({
                title: "Apakah Kamu Yakin?",
                text: "Klik OK, Maka Data Kamu Ubah Tidak Dapat DiKembalikan",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((approve) => {
                if (approve) {
                    // General form update_data(url,data,form)
                    update_data(url,data,form);
                }
            });
            
        });

    });

    //

    //EDIT BUTTON VIEW
    function buttonEdit(id) {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $("input[name='_token']").val()
            }
        });
        $.ajax({
            type: "GET",
            url: "{{ route('claim.edit',['claim'=>1]) }}",
            data: {
                id: id
            },
            success: function (data) {
                if (data) {

                    clear_error();
                    
                    $("#idApprove").val(data.id_reimbursement);

                } 
            },
            error: function(response) {
                try {
                    $.toast({
                        heading: 'Danger',
                        text: 'Gagal mendapatkan data terkait.',
                        showHideTransition: 'slide',
                        icon: 'error',
                        loaderBg: '#f2a654',
                        position: 'top-right'
                    })
                } catch (err) {

                }

            }
        });
    }

</script>

@endsection

@include('reimbursement.validation.validation_modal')

resources/views/reimbursement/validation/validation_modal.blade.php
@section('modal')
<!-- Modal Start Update Data Approve -->
<div class="modal fade" id="showModalUpdateApprove" tabindex="-1" role="dialog"
aria-labelledby="ApproveModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="ApproveModalLabel">Approve</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form class="forms-sample" method="POST" action="#" id="formUpdateApprove" enctype="multipart/form-data">
            @method('patch')
            <input type="hidden" value="{{ csrf_token() }}" name="_token" />
            <input type="hidden" id="idApprove" name="id" >
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group row">
                            <label style="padding-top: 5px;" class="col-sm-3 col-form-label">Reference Number
                                    <span class="" style="color:red;">*</span>
                            </label>
                            <div class="col-sm-9">
                                <div class="text-left" id="error_u_reference_number" style="padding: 2px; color:red;"></div>
                                <input style="border-radius: 15px;" type="text"
                                    class="form-control form-control-sm" name="reference_number"
                                    id="Updatereference_number" placeholder="Reference Number"
                                    aria-label="Reference Number"
                                />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-outline-success btn-fw"
                    style="border-radius: 21px;">Update</button>
                <button type="button" class="btn btn-outline-danger btn-fw"
                    style="border-radius: 21px;" data-dismiss="modal"
                    id="btnCloseModalApproveUpdate">Cancel</button>
            </div>
        </form>
    </div>
</div>
</div>
<!-- Modal End Update Data Approve -->
@endsection