routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* =========== MIDDLEWARE AUTH =========== */
Route::middleware(['web'])->group(function () {
    
        /* ===== LOGIN PAGE ===== */
    Route::get('/', function () {
        return view('auth.login');
    })->name('login_view')->middleware('guest');

    Route::post('login','EmployeeController@login_post')->name('login');

    Route::middleware(['auth'])->group(function () {
        /* =========== DASHBOARD =========== */
        Route::get('dashboard','DashboardController@index')->name('dashboard');

        /* =========== AUTH =========== */
        Route::get('logout','EmployeeController@logout')->name('logout');
        /* =========== END AUTH =========== */

        /* =========== MASTER =========== */
        Route::middleware(['role:superadmin'])->group(function () {
            Route::resources([
                'employee'           => 'EmployeeController',
                'benefit'            => 'BenefitController',
            ]);
        });

        Route::middleware(['role:superadmin,finance,employee'])->group(function () {
            Route::resources([
                'claim'      => 'ReimbursementController',
            ]);

            Route::get('get_tr_benefit','TrBenefitController@create')->name('get_tr');
        });

        Route::middleware(['role:superadmin,finance'])->group(function () {
            Route::get('index_validation','ReimbursementController@index_validation')->name('index_val');
            Route::patch('approve/{approve}','ReimbursementController@approve')->name('approve');
            Route::delete('reject/{id}','ReimbursementController@reject')->name('reject');
        });
        
    });

});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableInterface;

class Employee extends Authenticatable 
{
    use HasFactory;
    
    protected $table = 'employee';
    
    protected $primaryKey = 'id_employee';
    
    public $incrementing = true;
    
    public $timestamps = true;
    
    protected $hidden = [
        'password',
    ];

    public $fillable = [
        'email',
        'password',
        'name',
        'gender',
        'date_of_birth',
        'address',
        'position',
        'created_at',
        'updated_at'
    ];

    public function hasRole($role,$id)
    {
        return Employee::where('position', $role)->where('id_employee',$id)->get();
    }

    public function objtrbenefit()
    {
        return $this->hasMany(Tr_benefit::class, 'id_employee', 'id_employee');
    }

}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Carbon\Carbon;

use App\Models\Employee;
use App\Models\Benefit;
use App\Models\Tr_benefit;
use Yajra\Datatables\Datatables;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('master.employee.employee');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $employee = Employee::orderBy('created_at','desc')->get();
        return Datatables::of($employee)->make(true);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation_value = [
            'name'            => 'required|regex:/^[a-zA-Z ]+$/|min:5|max:50',
            'email'           => 'required|email|min:5|max:30|unique:employee',
            'password'        => 'required|min:6|max:25',
            'repassword'      => 'required|same:password',
            'employeegender'  => 'required',
            'date_of_birth'   => 'required',
            'address'         => 'required',
            'position'        => 'required',
        ];

        $validator = Validator::make($request->all(),$validation_value);

        if ($validator->fails()) {
            return response()->json(['message'=>'Gagal menambah data','errors' => $validator->errors()],422);
        }

        $data = [
            "name"          => $request->name,
            "email"         => $request->email,
            "password"      => Hash::make($request->password),
            "gender"        => $request->employeegender,
            "date_of_birth" => $request->date_of_birth,
            "position"      => $request->position,
            "address"       => $request->address
        ];

        $insert = Employee::create($data);

        
        if($insert){

            //Initialise benefit for employee
            $benefitemployee = $request->benefitemployee;

            if(count($benefitemployee) > 0 ){

                for ($i=0; $i < count($benefitemployee); $i++) { 
                    
                    $current_benefit = Benefit::where('id_benefit',$benefitemployee[$i])->get()->first();

                    $tr_benefit = [
                        'id_employee'        => $insert->id_employee,
                        'id_benefit'         => $benefitemployee[$i],
                        'beginning_balance'  => $current_benefit->balance,
                        'adjustment_balance' => 0,
                        'used_balance'       => 0,
                        'current_balance'    => $current_benefit->balance,
                    ];

                    $insert_tr = Tr_benefit::create($tr_benefit);
                
                }

            }

            return response()->json(['message'=>'Berhasil menambah data!'],200);
        
        }else{
            return response()->json(['message'=>'Gagal menambah data','errors' => $insert],422);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $Employee = Employee::find($request->id);
        return response()->json($Employee);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee,Request $request)
    {
        $Employee = Employee::with('objtrbenefit')->find($request->id);
        return response()->json($Employee);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $id = $request->id;

        $employee = Employee::where('id_employee',$id)->get()->first();

        $data = [
            "name"          => $request->name,
            "email"         => $request->email,
            "gender"        => $request->employeegender,
            "date_of_birth" => $request->date_of_birth,
            "position"      => $request->position,
            "address"       => $request->address
        ];

        $validation_value = [
            'name'            => 'required|regex:/^[a-zA-Z ]+$/|min:5|max:50',
            'email' =>
            [
                'required',
                'min:5',
                'max:30',
                Rule::unique('employee')->ignore($id,'id_employee')
            ],
            'employeegender'  => 'required',
            'date_of_birth'   => 'required',
            'address'         => 'required',
            'position'        => 'required',
        ];

        if(!empty($request->password)){
            $validation_value += [
                'password' => 'required|min:6|max:25',
                'repassword' => 'required|same:password'
            ];
            $data += [
                'password' => Hash::make($request->password)
            ];
        }

        if(!empty($request->email) ){
            if($request->email != $employee->email){
                $validation_value +=  [
                    'email'           => 'required|email|min:5|max:30|unique:employee',
                ];
                $data += [
                    'email' => $request->email
                ];
            }
        }else{
            $validation_value +=  [
                'email'           => 'required|email|min:5|max:30|unique:employee',
            ];
        }

        $validator = Validator::make($request->all(),$validation_value);

        if ($validator->fails()) {
            return response()->json(['message'=>'Gagal mengubah data','errors' => $validator->errors()],422);
        }

        $update = Employee::where('id_employee',$id)->update($data);

        if($update){

            $benefitemployee = ($request->benefitemployee == null ? [] : $request->benefitemployee );
      
            $current_benefit = Tr_benefit::select('id_benefit')
                                        ->where('id_employee',$id)
                                        ->where(DB::raw('YEAR(created_at)'), '=', Carbon::now()->format('Y'))
                                        ->get();

            $current_benefit = $current_benefit->map(function ($value) {
                return (string) $value["id_benefit"];
            })->toArray();
            
            $out = array_diff($current_benefit,$benefitemployee);
            $in  = array_diff($benefitemployee,$current_benefit);
            //Benefit In
            if(count($in)>0){

                foreach ($in as $key => $value) {
                    
                    $current_benefit = Benefit::where('id_benefit',$value)->get()->first();
                    
                    $tr_benefit = [
                        'id_employee'        => $id,
                        'id_benefit'         => $value,
                        'beginning_balance'  => $current_benefit->balance,
                        'adjustment_balance' => 0,
                        'used_balance'       => 0,
                        'current_balance'    => $current_benefit->balance,
                    ];

                    $insert_tr = Tr_benefit::create($tr_benefit);
                }
              
            }
           
            //Benefit Out
            if(count($out) > 0){
                foreach ($out as $key => $value) {
                    $out_tr = Tr_benefit::where('id_benefit',$value)->where('id_employee',$id)->first()->delete();
                } 
            }


            return response()->json(['message'=>'Berhasil mengubah data'],200);
        }else{
            return response()->json(['message'=>'Gagal mengubah data','errors' => $update],422);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $employee = Employee::find($id);
        $employee->delete();
    }

    public function login_post(Request $request){

        $identity = $request->email;
        $password = $request->password;

        if (Auth::attempt([
            filter_var($identity, FILTER_VALIDATE_EMAIL) ? 'email' : 'name' => $identity, 'password' => $request->password
            ]))
        {
            return redirect()->route('dashboard');
        }else{
            return redirect()->route('login_view')
                            ->withErrors(['login' => 'The email or password you’ve entered is incorrect.!'])
                            ->withInput();
        }
    }

    public function logout(){
        Auth::logout();

        return redirect()->route('login_view')->withErrors(['logout' => 'Berhasil keluar dari sistem!']);
    }

}

resources/views/master/employee/employee.blade.php
@extends('layouts.dashboard')
@section('content')
<!-- Tittle -->
<div class="row">
    <div style="margin-bottom: 0.2rem;" class="col-12 grid-margin">
        <div style="height: 65px; border-radius: 15px;" class="card">
            <div class="card-body">
                <div style="display: flex; align-items: flex-start; justify-content: space-between; height: 40px;">
                    <h4 class="card-title" style="font-size: 2rem; font-weight: 300; margin-bottom: 0px;">Employee</h4>
                    {{-- <button type="button" class="btn btn-success btn-rounded btn-icon" data-toggle="tooltip" data-placement="top" data-custom-class="tooltip-success" title="EDIT" data-target="#showModalUpdateAssetClass" style="margin-right:5px;"><i style="font-size:1.5rem; margin-left:-7px;" class="ti-pencil-alt"></i></button> --}}
                    <button style="margin: -0.2rem .05rem -1rem auto;" type="button" class="btn btn-primary btn-sm"
                        data-toggle="modal" data-target="#showModalInsertEmployee"><i
                            class="ti-plus menu-icon"></i>&ensp;
                        ADD</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Table -->
<div class="row">
    <div style="margin-bottom: 0.2rem;" class="col-12 grid-margin">
        <div class="card" style="border-radius: 15px;">
                <div class="card-body">
                {{-- <h4 class="card-title">Data table</h4> --}}
                <div class="row">
                    <div class="col-12">
                    <div class="table-responsive">
                        <table id="employeeTable" class="table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Gender</th>
                                <th>Date of Birth</th>
                                <th>Email</th>
                                <th>Address</th>
                                <th>Position</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        </table>
                    </div>
                    </div>
                </div>
                </div>
            </div>
    </div>
</div>
{{-- Table End --}}
@endsection

@section('jscustom')

<script>
    
    var mTable;

    $(document).ready(function () {
        //INITIALISE SELECT2
        get_benefit();
        $("#benefitemployee").select2({
            tags: true,
            width: '19rem',
            dropdownParent: $("#formInputEmployee")
        });

        $("#Updatebenefitemployee").select2({
            tags: true,
            width: '19rem',
            dropdownParent: $("#formUpdateEmployee")
        });
        
        //RENDER DATA TABLES
        mTable = $('#employeeTable').DataTable({
            responsive: true,
            processing: true,
            "language": {
                "processing": "<div class='dot-opacity-loader'></div>"
            },
            "order": [[ 0, "desc" ]],
            serverSide: true,
            ajax: "{{ route('employee.create')}}",
            dom: 'Bfrtip',
            buttons: [
              
            ],
            columns: [
                {  
                    data: 'id_employee',
                    render: function (data, type, row, meta) {
                        return meta.row + meta.settings._iDisplayStart + 1;
                    }
                },
                {
                    data: 'name',
                    name: 'name'
                },
                {
                    data: 'date_of_birth',
                    name: 'date_of_birth'
                },
                {  
                    data: 'gender',
                    render: function (data, type, row, meta) {
                        return (data == 1 ? 'Man': 'Women');
                    }
                },
                {
                    data: 'email',
                    name: 'email'
                },
                {
                    data: 'address',
                    name: 'address'
                },
                {
                    data: 'position',
                    name: 'position'
                },
                {
                    data: 'id_employee',
                    render: function (data, type, row) {
                        let buttonEdit =
                            '<button type="button" class="btn btn-success btn-rounded btn-icon" data-toggle="modal" data-placement="buttom" data-custom-class="tooltip-success" title="EDIT" data-target="#showModalUpdateEmployee" style="margin-right:5px;" onclick="buttonEdit(\'' + data + '\');"><i style="font-size:1.5rem; margin-left:-7px;" class="ti-pencil-alt"></i></button>';
                        let buttonHapus =
                            '<button type="button" class="btn btn-danger btn-rounded btn-icon" data-toggle="tooltip" data-placement="bottom" data-custom-class="tooltip-success" title="DELETE" onclick="delete_data(\''+
                            data +'\',\'employee\');"><i style="font-size:1.5rem; margin-left:-8px;" class="ti-trash"></i></button>';
                        return buttonEdit + buttonHapus;
                    }
                }
            ]
        });

        //INSERT Departement
        $('#formInputEmployee').on('submit', function (e) {
            e.preventDefault();

            var url,data,form;

            url = 'employee';           //For routing
            data = $(this).serialize();    // Data Form
            form = 'Employee';          //Reset Trigger and Close Modal

            // General form insert_data(url,data,form)
            insert_data(url,data,form);
        });

        //UPDATE Departement
        $('#formUpdateEmployee').on('submit', function (e) {

            e.preventDefault();
            var url,data,form;

            url = 'employee';           //For routing
            data = $(this).serialize(); // Data Form
            form = 'Employee';          // Reset Trigger and Close Modal

            // General form update_data(url,data,form)
            update_data(url,data,form);
        });

    });

    //
    function get_benefit(){
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
            }
        });
        $.ajax({
            type: "GET",
            url: "{{route('benefit.create')}}",
            success: function (data) {
                $.each(data.data, function (index, value) {
                    $('#benefitemployee').append('<option id=' + value.id_benefit + ' value=' + value.id_benefit +
                        '>' + value.benefit_name +'</option>')
                });
                $.each(data.data, function (index, value) {
                    $('#Updatebenefitemployee').append('<option id=' + value.id_benefit + ' value=' + value.id_benefit +
                        '>' + value.benefit_name +'</option>')
                });
            },
            error: function(response) {
                try {
                    $.toast({
                        heading: 'Danger',
                        text: 'Gagal mendapatkan data terkait.',
                        showHideTransition: 'slide',
                        icon: 'error',
                        loaderBg: '#f2a654',
                        position: 'top-right'
                    })
                } catch (err) {

                }
            }
        });
    }

    //EDIT BUTTON VIEW
    function buttonEdit(id) {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $("input[name='_token']").val()
            }
        });
        $.ajax({
            type: "GET",
            url: "{{ route('employee.edit',['employee'=>1]) }}",
            data: {
                id: id
            },
            success: function (data) {
                if (data) {

                    clear_error();

                    let current_benefit = data.objtrbenefit;
                    //Set benefit values
                    let selectedValues = new Array();
                    let index = 0;
                    
                    $("#idEmployee").val(data.id_employee);
                    $("#Updatename").val(data.name)
                    $("#Updateemail").val(data.email)
                    $("#Updateemployeegender").val(data.gender)
                    $("#Updatedate_of_birth").val(data.date_of_birth)
                    $("#Updateposition").val(data.position)
                    $("#Updateaddress").val(data.address)

                    $.each(current_benefit, function (index, value) {
                        selectedValues[index] = value.id_benefit
                        index++;
                    });
                    
                    $('#Updatebenefitemployee').val(selectedValues).change();
                } 
            },
            error: function(response) {
                try {
                    $.toast({
                        heading: 'Danger',
                        text: 'Gagal mendapatkan data terkait.',
                        showHideTransition: 'slide',
                        icon: 'error',
                        loaderBg: '#f2a654',
                        position: 'top-right'
                    })
                } catch (err) {

                }

            }
        });
    }

</script>

@endsection

@include('master.employee.employee_modal')