routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* =========== MIDDLEWARE AUTH =========== */
Route::middleware(['web'])->group(function () {
    
        /* ===== LOGIN PAGE ===== */
    Route::get('/', function () {
        return view('auth.login');
    })->name('login_view')->middleware('guest');

    Route::post('login','EmployeeController@login_post')->name('login');

    Route::middleware(['auth'])->group(function () {
        /* =========== DASHBOARD =========== */
        Route::get('dashboard','DashboardController@index')->name('dashboard');

        /* =========== AUTH =========== */
        Route::get('logout','EmployeeController@logout')->name('logout');
        /* =========== END AUTH =========== */

        /* =========== MASTER =========== */
        Route::middleware(['role:superadmin'])->group(function () {
            Route::resources([
                'employee'           => 'EmployeeController',
                'benefit'            => 'BenefitController',
            ]);
        });

        Route::middleware(['role:superadmin,finance,employee'])->group(function () {
            Route::resources([
                'claim'      => 'ReimbursementController',
            ]);

            Route::get('get_tr_benefit','TrBenefitController@create')->name('get_tr');
        });

        Route::middleware(['role:superadmin,finance'])->group(function () {
            Route::get('index_validation','ReimbursementController@index_validation')->name('index_val');
            Route::patch('approve/{approve}','ReimbursementController@approve')->name('approve');
            Route::delete('reject/{id}','ReimbursementController@reject')->name('reject');
        });
        
    });

});

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Welcome to the Systems!</title>
  @yield('link')
  <!-- plugins:css -->
  <link rel="stylesheet" href="{{ asset('vendors/iconfonts/font-awesome/css/font-awesome.min.css') }}"/>
  <link rel="stylesheet" href="{{ asset('vendors/iconfonts/ti-icons/css/themify-icons.css') }}">
  <link rel="stylesheet" href="{{ asset('vendors/css/vendor.bundle.base.css') }}">
  <link rel="stylesheet" href="{{ asset('vendors/css/vendor.bundle.addons.css') }}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <link rel="stylesheet" href="{{ asset('vendors/lightgallery/css/lightgallery.css') }}">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{{ asset('css/vertical-layout-light/style.css') }}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{{ asset('images/favicon.png') }}" />
  
</head>
<body class="sidebar-dark">
  <div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    @include('layouts.navbar')
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_settings-panel.html -->
      @include('layouts.setting')
      <!-- partial -->
      <!-- partial:partials/_sidebar.html -->
      @include('layouts.sidebar')
      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
            @yield('content')
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        @include('layouts.footer')
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->

  <!-- plugins:js -->
  <script src="{{ asset('vendors/js/vendor.bundle.base.js') }}"></script>
  <script src="{{ asset('vendors/js/vendor.bundle.addons.js') }}"></script>
  <script src="{{ asset('js/lodash.js') }}"></script>
  <script src="{{ asset('js/jquery.steps.js') }}"></script>
  <script src="{{ asset('js/jquery.steps.min.js') }}"></script>
  <script src="{{ asset('vendors/lightgallery/js/lightgallery-all.min.js') }}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <!-- End plugin js for this page-->
  <!-- inject:js -->
  <script src="{{ asset('js/off-canvas.js') }}"></script>
  <script src="{{ asset('js/hoverable-collapse.js') }}"></script>
  <script src="{{ asset('js/template.js') }}"></script>
  <script src="{{ asset('js/settings.js') }}"></script>
  <script src="{{ asset('js/todolist.js') }}"></script>
  <script src="{{ asset('js/dashboard.js') }}"></script>
  <script src="{{ asset('js/form-validation.js') }}"></script>

  <!-- Form -->
  <script src="{{ asset('js/file-upload.js') }}"></script>
  <script src="{{ asset('js/typeahead.js') }}"></script>

 <!-- Table -->
  <script src="{{ asset('js/buttons.html5.min.js') }}" type="text/javascript"></script>
  <script src="{{ asset('dattables/dataTables.buttons.min.js') }}" type="text/javascript"></script>
  <script src="{{ asset('dattables/jszip.min.js') }}" type="text/javascript"></script>
  <script src="{{ asset('dattables/pdfmake.min.js') }}" type="text/javascript"></script>
  <script src="{{ asset('js/buttons.flash.min.js') }}" type="text/javascript"></script>
  <script src="{{ asset('dattables/vfs_fonts.js') }}" type="text/javascript"></script>

 <!-- Tooltip -->
  <script src="{{ asset('js/tooltips.js') }}"></script>
  <script src="{{ asset('js/popover.js') }}"></script>
  <!-- endinject -->

  <!-- Global js for all page -->
  @include('layouts.js')
  <!-- End global js for all page-->

  <!-- Custom js for this page-->
  @yield('jscustom')
  <!-- End custom js for this page-->

  <!-- Custom js for this page-->
  @yield('modal')
  <!-- End custom js for this page -->

</body>

</html>

resources/views/layouts/footer.blade.php
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021 <a href="https://www.linkedin.com/in/imam-taufiq-ponco-28b56a148/" target="_blank">Imam Taufiq Ponco</a>. All rights reserved.</span>
      {{-- <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="ti-heart text-danger ml-1"></i></span> --}}
    </div>
</footer>

resources/views/layouts/js.blade.php
{{-- GLOBAL JS IS USE FOR ALL MODULE --}}
<script>
    @php $prefix = url('/')."/"; @endphp

    //FIXING MODAL BUGS
    $('body').on('hidden.bs.modal', function () {
        if($('.show').length > 1)
        {
            $('body').addClass('modal-open');
        }
    });

    // CLEAR FORM INPUT
    function clear_form(){
        var form = $("form");
        // var disabled = form.find(':input:disabled').removeAttr('disabled');
        // var select = form.find('select').removeAttr('disabled').text('').val('');
        form.trigger("reset");
        // disabled.attr('disabled','disabled');
    }

    //RESET ERROR
    function clear_error(){
        $('.text-left').html('');
    }

    //ERROR HANDLER
    function error_handler(data,status){
      
		var testing = 0;

		$('.text-left').html('');

		for (let [key, value] of Object.entries(data)) {
			if(status == 'u'){
				testing = `${key}`.split(".");
			    if(testing[1]==0){
			        $('#error_u_'+testing[0]).html(`${value}`)
			    }else{
			       	$('#error_u_'+`${key}`).html(`${value}`)
			    }

			}else{
			    testing = `${key}`.split(".");
			    if(testing[1]==0){
			        $('#error_'+testing[0]).html(`${value}`)
			    }else{
			        $('#error_'+`${key}`).html(`${value}`)
			    }

			}
		}
    }

    //INSERT DATA
    // General form insert_data(url,data,form)
    // url = 'location';           For routing
    // data = $(this).serialize(); Data Form
    // form = 'Location';          Reset Trigger and Close Modal
    function insert_data(url,data,form){
        
        $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': "{{ csrf_token() }}"
                }
        });

        $.ajax({
                type: "POST",
                url: "{{ $prefix }}" + url ,
                data: data,
                success: function (response) {

                    $('#formInput'+form).trigger("reset");
                    clear_error();
                    clear_form();
                    mTable.ajax.reload();

                    $.toast({
                        heading: 'Success',
                        text: response.message,
                        showHideTransition: 'slide',
                        icon: 'success',
                        loaderBg: '#f96868',
                        position: 'top-right'
                    })
                    console.log(form);
                    $('#btnCloseModal'+form+'Insert').click();

                },
                error: function(response) {

                    var errors = response.responseJSON.errors;

                    try {
                        error_handler(errors,'s');
                    } catch (err) {

                    }

                    $.toast({
                        heading: 'Danger',
                        text: response.responseJSON.message,
                        showHideTransition: 'slide',
                        icon: 'error',
                        loaderBg: '#f2a654',
                        position: 'top-right'
                    })
                }
            });

    }

    //UPDATE DATA
    function update_data(url,data,form){

            id = $('input[id="id'+form+'"]').val();
            console.log(id,form)
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': "{{ csrf_token() }}"
                }
            });

            $.ajax({
                type: "PATCH",
                url: "{{ $prefix }}"+ url + '/' + id,
                data: data,
                success: function (response) {

                    $('#formUpdate'+form).trigger("reset");
                    clear_error();
                    clear_form();
                    mTable.ajax.reload();

                    $.toast({
                        heading: 'Success',
                        text: response.message,
                        showHideTransition: 'slide',
                        icon: 'success',
                        loaderBg: '#f96868',
                        position: 'top-right'
                    })

                    $('#btnCloseModal'+form+'Update').click();

                },
                error: function(response) {

                    var errors = response.responseJSON.errors;

                    try {
                        error_handler(errors,'u');
                    } catch (err) {

                    }

                    $.toast({
                        heading: 'Danger',
                        text: response.responseJSON.message,
                        showHideTransition: 'slide',
                        icon: 'error',
                        loaderBg: '#f2a654',
                        position: 'top-right'
                    })
                }
            });
    }

    //DELETE DATA
    function delete_data(id,url){
        swal({
                title: "Apakah Kamu Yakin?",
                text: "Klik OK, Maka Data Kamu Tidak Dapat DiKembalikan",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {

                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': "{{ csrf_token() }}"
                    }
                });

                $.ajax({
                    url: "{{ $prefix }}"+ url +"/"+ id,
                    method: 'post',
                    data: {
                        _method: "DELETE",
                        _token: "{{ csrf_token() }}",
                    },
                        success: function(result){
                            $.toast({
                                heading: 'Success',
                                text: 'Berhasil menghapus data terkait.',
                                showHideTransition: 'slide',
                                icon: 'success',
                                loaderBg: '#f96868',
                                position: 'top-right'
                            })
                            mTable.ajax.reload();
                        },
                        error: function(data) {
                            console.log(data)
                        }
                    });
                } else {
                    $.toast({
                        heading: 'Warning',
                        text: 'Batal Menghapus Data',
                        showHideTransition: 'slide',
                        icon: 'warning',
                        loaderBg: '#57c7d4',
                        position: 'top-right'
                    })
                    $('#btnCloseModalInsert').click();
                }
        });
    }

    //INSERT DATA
    // General form insert_data(url,data,form)
    // url = 'location';           For routing
    // data = $(this).serialize(); Data Form
    // form = 'Location';          Reset Trigger and Close Modal
    function insert_data_file(url,data,form){
        
        $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': "{{ csrf_token() }}"
                }
        });

        $.ajax({
                type: "POST",
                url: "{{ $prefix }}" + url ,
                contentType: false,
                processData: false,
                data: data,
                success: function (response) {

                    $('#formInput'+form).trigger("reset");
                    clear_error();
                    clear_form();
                    mTable.ajax.reload();

                    $.toast({
                        heading: 'Success',
                        text: response.message,
                        showHideTransition: 'slide',
                        icon: 'success',
                        loaderBg: '#f96868',
                        position: 'top-right'
                    })
                    console.log(form);
                    $('#btnCloseModal'+form+'Insert').click();

                },
                error: function(response) {

                    var errors = response.responseJSON.errors;

                    try {
                        error_handler(errors,'s');
                    } catch (err) {

                    }

                    $.toast({
                        heading: 'Danger',
                        text: response.responseJSON.message,
                        showHideTransition: 'slide',
                        icon: 'error',
                        loaderBg: '#f2a654',
                        position: 'top-right'
                    })
                }
            });

    }

    //UPDATE DATA
    function update_data_file(url,data,form){

        id = $('input[id="id'+form+'"]').val();

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': "{{ csrf_token() }}"
            }
        });

        $.ajax({
            type: "POST",
            url: "{{ $prefix }}"+ url + '/' + id,
            contentType: false, // NEEDED, DON'T OMIT THIS (requires jQuery 1.6+)
            processData: false,
            data: data,
            success: function (response) {

                $('#formUpdate'+form).trigger("reset");
                clear_error();
                
                mTable.ajax.reload();

                $.toast({
                    heading: 'Success',
                    text: response.message,
                    showHideTransition: 'slide',
                    icon: 'success',
                    loaderBg: '#f96868',
                    position: 'top-right'
                })

                $('#btnCloseModal'+form+'Update').click();	
            },
            error: function(response) {

                var errors = response.responseJSON.errors;

                try {
                    error_handler(errors,'u');
                } catch (err) {

                }

                $.toast({
                    heading: 'Danger',
                    text: response.responseJSON.message,
                    showHideTransition: 'slide',
                    icon: 'error',
                    loaderBg: '#f2a654',
                    position: 'top-right'
                })
            }
        });
    }
    

</script>

resources/views/layouts/navbar.blade.php
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
      <a class="navbar-brand brand-logo mr-5" href="{{ url('dashboard') }}"><img src="{{ asset('images/logo-white.svg') }}" alt="logo"/></a>
      <a class="navbar-brand brand-logo-mini" href="{{ url('dashboard') }}"><img src="{{ asset('images/logo-mini.svg') }}" alt="logo"/></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
      <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
        <span class="ti-layout-grid2"></span>
      </button>
      <ul class="navbar-nav mr-lg-2">
        {{-- <li class="nav-item nav-search d-none d-lg-block">
          <div class="input-group">
            <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
              <span class="input-group-text" id="search">
                <i class="ti-search"></i>
              </span>
            </div>
            <input type="text" class="form-control" id="navbar-search-input" placeholder="Search now" aria-label="search" aria-describedby="search">
          </div>
        </li> --}}
      </ul>
      <ul class="navbar-nav navbar-nav-right">
        {{-- <li class="nav-item dropdown mr-1">
          <a class="nav-link count-indicator dropdown-toggle d-flex justify-content-center align-items-center" id="messageDropdown" href="#" data-toggle="dropdown">
            <i class="ti-email mx-0"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
            <p class="mb-0 font-weight-normal float-left dropdown-header">Messages</p>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                  <img src="https://via.placeholder.com/36x36" alt="image" class="profile-pic">
              </div>
              <div class="preview-item-content flex-grow">
                <h6 class="preview-subject ellipsis font-weight-normal">David Grey
                </h6>
                <p class="font-weight-light small-text text-muted mb-0">
                  The meeting is cancelled
                </p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                  <img src="https://via.placeholder.com/36x36" alt="image" class="profile-pic">
              </div>
              <div class="preview-item-content flex-grow">
                <h6 class="preview-subject ellipsis font-weight-normal">Tim Cook
                </h6>
                <p class="font-weight-light small-text text-muted mb-0">
                  New product launch
                </p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                  <img src="https://via.placeholder.com/36x36" alt="image" class="profile-pic">
              </div>
              <div class="preview-item-content flex-grow">
                <h6 class="preview-subject ellipsis font-weight-normal"> Johnson
                </h6>
                <p class="font-weight-light small-text text-muted mb-0">
                  Upcoming board meeting
                </p>
              </div>
            </a>
          </div>
        </li> --}}
        {{-- <li class="nav-item dropdown">
          <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
            <i class="ti-bell mx-0"></i>
            <span class="count"></span>
          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
            <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-success">
                  <i class="ti-info-alt mx-0"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <h6 class="preview-subject font-weight-normal">Application Error</h6>
                <p class="font-weight-light small-text mb-0 text-muted">
                  Just now
                </p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-warning">
                  <i class="ti-settings mx-0"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <h6 class="preview-subject font-weight-normal">Settings</h6>
                <p class="font-weight-light small-text mb-0 text-muted">
                  Private message
                </p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-info">
                  <i class="ti-user mx-0"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <h6 class="preview-subject font-weight-normal">New user registration</h6>
                <p class="font-weight-light small-text mb-0 text-muted">
                  2 days ago
                </p>
              </div>
            </a>
          </div>
        </li> --}}
        <li class="nav-item nav-profile dropdown">
          <a class="nav-link" href="#" data-toggle="dropdown" id="profileDropdown">
            <img src="{{ asset('images/albert.jpg') }}" alt="profile"/>
          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
            <a class="dropdown-item" href="{{ route('logout') }}">
              <i class="ti-power-off text-primary"></i>
              Logout
            </a>
          </div>
        </li>
        {{-- <li class="nav-item nav-settings d-none d-lg-flex">
          <a class="nav-link" href="#">
            <i class="ti-more"></i>
          </a>
        </li> --}}
      </ul>
      <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
        <span class="ti-layout-grid2"></span>
      </button>
    </div>
  </nav>

resources/views/layouts/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="{{ url('dashboard') }}">
          <i class="ti-home menu-icon"></i>
          <span class="menu-title">Dashboard</span>
        </a>
      </li>
      @if(Auth::user()->position == 'superadmin')
      <li class="nav-item">
        <a class="nav-link" data-toggle="collapse" href="#ui-advanced" aria-expanded="false" aria-controls="ui-advanced">
          <i class="ti-view-list menu-icon"></i>
          <span class="menu-title">Master</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="ui-advanced">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="{{ route('employee.index') }}">Employee</a></li>
            <li class="nav-item"> <a class="nav-link" href="{{ route('benefit.index') }}">Benefit</a></li>
            {{-- <li class="nav-item"> <a class="nav-link" href="{{ route('account.index') }}">Employee</a></li> --}}
          </ul>
        </div>
      </li>
      @endif
     
      <li class="nav-item">
        <a class="nav-link" data-toggle="collapse" href="#form-elements" aria-expanded="false" aria-controls="form-elements">
          <i class="ti-clipboard menu-icon"></i>
          <span class="menu-title">Reimbursement</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="form-elements">
          <ul class="nav flex-column sub-menu">
            @if(Auth::user()->position != 'finance')
              <li class="nav-item"> <a class="nav-link" href="{{route('claim.index')}}">Request</a></li>
            @endif
            @if(Auth::user()->position != 'employee')
              <li class="nav-item"><a class="nav-link" href="{{route('index_val')}}">Validation</a></li>
            @endif
          </ul>
        </div>
      </li>
    </ul>
  </nav>